### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by ghane** [routeviews/issues#100]
### Full Name

Sanjeev Gupta

### ASN

37989

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

203.123.48.6
2405:fc0::6

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by pfsinoz** [comment]
Hello Sanjeev, our apologies for taking so long to respond to setting up this multi-hop peering while we increased our capacity on our University of Oregon collectors. If you are still interested, please let me know, and I'll set up the peering and provide you with details. Thanks for your interest in the RouteViews project.

**Comment by ghane** [comment]
Hi Philip,

We are a leaf node, multihomed via two Tier 2 local ISPs, and peering at
SGIX.

We host CAIDA, RIPE, and other probes.

If this view of the Internet is useful to your project, I would be happy to
set up a session.

203.123.48.6
2405:fc00::6
AS37989
No MD5 preferred
The Router facing you is a Mikrotik, if that is relevant.

Our import filters are loose, so please don't send us any routes or
updates, except for reachability test nets :-)

**Comment by pfsinoz** [comment]
Thanks Sanjeev! Should be no issue with you using Mikrotik. :-)  We don't send any routes or BGP updates, and we also don't accept (or send) add-path (which some implementations seem to do by default). Nice to see that you are hosting CAIDA and RIPE probes too!

Our collector details are:

IPv4: 128.223.51.113
IPv6: 2001:468:d01:33::113
ASN: 6447
FQDN: route-views7.routeviews.org

I've set up the EBGP multihop sessions now:
```
Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
203.123.48.6    4      37989         0         1        0    0    0    never       Active        0 DCS1 Pte Ltd
2405:fc00::6    4      37989         0         0        0    0    0    never       Active        0 DCS1 Pte Ltd
```
Please let us know if you have any issues with bringing up the BGP sessions.

Many thanks for supporting RouteViews!

**Comment by ghane** [comment]
Hi,

I set this up last week, but the session did not come up, and I assumed it
would.

Checked today.  We are unable to reach you, although we do have a route for
the /16 from our transit provider:

***@***.*** > /tool/traceroute use-dns=yes 128.223.51.113
Columns: ADDRESS, LOSS, SENT, LAST, AVG, BEST, WORST, STD-DEV
 #  ADDRESS                              LOSS  SENT  LAST     AVG    BEST
WORST  STD-DEV
 1  fnet221-f60-60-access.vqbn.com.sg.   0%       5  0.3ms    0.5    0.3
 1      0.3
 2  losangeles1.vqbn.com.                0%       5  165.5ms  165.6  165.5
 166    0.2
 3  port-ptck-pe-02.net.linkoregon.org.  0%       5  193.4ms  193.6  193.4
 193.8  0.1
 4  eugn-oh-pe-02.net.linkoregon.org.    0%       5  195.9ms  196    195.9
 196.1  0.1
 5  uo-oh-gw.net.linkoregon.org.         0%       5  196.1ms  196.5  196.1
 196.8  0.2
 6                                       100%     5  timeout

 7                                       100%     5  timeout

 8                                       100%     5  timeout

 9                                       100%     5  timeout

10                                       100%     4  timeout



The same for your IPv6 address.

Can you traceroute to 203.123.48.6 , please?  Who is linkoregon.net ?

-- 
Sanjeev Gupta
+65 98551208     http://www.linkedin.com/in/ghane

**Comment by pfsinoz** [comment]
Hi Sanjeev,

Oh dear, hmmm, this is not good. But just to note that University of Oregon use a lot of private address space for their internal links, so you will only ever see as far as their border routers, and the endpoints that have public IP addresses. Unfortunately it makes troubleshooting tricky. Are you able to ping route-views7.routeviews.org at all?

LinkOregon is a backbone provider for the State of Oregon's public and non-profit sectors, and is the University of Oregon's transit provider - you can find more here: https://www.linkoregon.org/

As for the traceroute to 203.123.48.6:
```
pfs@route-views7:~$ traceroute 203.123.48.6
traceroute to 203.123.48.6 (203.123.48.6), 30 hops max, 60 byte packets
 1  vl-51-gw.uoregon.edu (128.223.51.1)  0.376 ms  0.657 ms  0.367 ms
 2  100.64.176.0 (100.64.176.0)  0.334 ms  0.324 ms  0.364 ms
 3  10.252.144.33 (10.252.144.33)  3.880 ms  3.865 ms  3.830 ms
 4  10.252.20.132 (10.252.20.132)  1.182 ms  1.325 ms  1.135 ms
 5  10.252.10.249 (10.252.10.249)  1.052 ms 10.252.9.249 (10.252.9.249)  5.835 ms 10.252.10.249 (10.252.10.249)  1.006 ms
 6  10.252.10.250 (10.252.10.250)  1.164 ms 10.252.9.250 (10.252.9.250)  0.987 ms 10.252.10.250 (10.252.10.250)  1.056 ms
 7  eugn-wix-pe-01.net.linkoregon.org (207.98.127.238)  1.051 ms eugn-oh-pe-02.net.linkoregon.org (207.98.127.249)  0.906 ms  1.202 ms
 8  port-ptck-pe-02.net.linkoregon.org (207.98.127.247)  3.773 ms eugn-oh-noc-gw.net.linkoregon.org (207.98.126.13)  3.806 ms port-ptck-pe-02.net.linkoregon.org (207.98.127.247)  3.989 ms
 9  * * eugn-oh-pe-01.net.linkoregon.org (207.98.126.76)  4.113 ms
10  * port-ptck-pe-01.net.linkoregon.org (207.98.126.79)  4.329 ms *
11  * port-ptck-pe-02.net.linkoregon.org (207.98.127.247)  4.177 ms  3.721 ms
12  * router6.dcs1.biz (203.123.48.6)  196.830 ms  196.771 ms
```
and the IPv6 traceroute is:
```
pfs@route-views7:~$ traceroute 2405:fc00::6
traceroute to 2405:fc00::6 (2405:fc00::6), 30 hops max, 80 byte packets
 1  2001:468:d01:33::1 (2001:468:d01:33::1)  0.703 ms  0.453 ms  0.392 ms
 2  fcfb:9d69:ef7f:9400::1 (fcfb:9d69:ef7f:9400::1)  0.668 ms  0.556 ms  0.635 ms
 3  vl-3462-gw.uoregon.edu (2607:8400:2efd:20::1)  4.560 ms  4.558 ms  4.546 ms
 4  2607:8400:2efd:d312::1 (2607:8400:2efd:d312::1)  1.171 ms 2607:8400:2efd:d412::1 (2607:8400:2efd:d412::1)  0.862 ms  1.023 ms
 5  2607:8400:2efd:caff::249 (2607:8400:2efd:caff::249)  5.777 ms  5.755 ms  2.441 ms
 6  2607:8400:2efd:c9fe::246 (2607:8400:2efd:c9fe::246)  1.721 ms 2607:8400:2efd:caff::250 (2607:8400:2efd:caff::250)  1.717 ms 2607:8400:2efd:cafe::246 (2607:8400:2efd:cafe::246)  1.098 ms
 7  eugn-oh-pe-02.net.linkoregon.org (2605:bc80:200f:a::1)  0.920 ms eugn-wix-pe-01.net.linkoregon.org (2605:bc80:200f:9::1)  0.983 ms eugn-oh-pe-02.net.linkoregon.org (2605:bc80:200f:a::1)  1.025 ms
 8  2001:550:2:1b::a:2 (2001:550:2:1b::a:2)  3.650 ms  3.742 ms *
 9  v6-six.vqbn.com (2001:504:16::46ba)  32.037 ms *  32.102 ms
10  * * *
11  * 2001:550:2:1b::a:2 (2001:550:2:1b::a:2)  3.978 ms *
12  * * v6-six.vqbn.com (2001:504:16::46ba)  32.289 ms
13  2001:d98:e:4::4 (2001:d98:e:4::4)  222.384 ms  197.505 ms *
14  * mikrotik-m.dcs1.biz (2405:fc00::6)  249.468 ms *
```
and I can ping your router as well:
```
pfs@route-views7:~$ ping 2405:fc00::6
PING 2405:fc00::6(2405:fc00::6) 56 data bytes
64 bytes from 2405:fc00::6: icmp_seq=2 ttl=49 time=245 ms
64 bytes from 2405:fc00::6: icmp_seq=3 ttl=49 time=246 ms
^C
--- 2405:fc00::6 ping statistics ---
4 packets transmitted, 2 received, 50% packet loss, time 3027ms
rtt min/avg/max/mdev = 244.721/245.152/245.583/0.431 ms
pfs@route-views7:~$ ping 203.123.48.6
PING 203.123.48.6 (203.123.48.6) 56(84) bytes of data.
64 bytes from 203.123.48.6: icmp_seq=1 ttl=54 time=197 ms
64 bytes from 203.123.48.6: icmp_seq=2 ttl=54 time=197 ms
64 bytes from 203.123.48.6: icmp_seq=3 ttl=54 time=197 ms
^C
--- 203.123.48.6 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 196.622/196.957/197.201/0.245 ms
```
I am getting these error messages when we try and open a BGP session with your router:
```
May 28 14:56:49 route-views7 bgpd[6853]: 203.123.48.6 [Error] bgp_read_packet error: Connection reset by peer
May 28 14:57:59 route-views7 bgpd[6853]: 2405:fc00::6 [Error] bgp_read_packet error: Connection reset by peer
```
which is basically a connection being refused by the remote peer. I have checked and we have the ebgp-multihop option configured at our end.

Hope this helps!

Philip

**Comment by ghane** [comment]
Philip,

(Traceroutes started working sometime last night)

I did the "IT Thing".  I deleted the session setup, rebooted, and created
them again.

Sessions are up now.

***@***.*** > /routing/bgp/session/print  where name ~ "Route*"
Flags: E - established
 8 E name="Routeview-v4-1"
     remote.address=128.223.51.113 .as=6447 .id=128.223.51.113
.capabilities=mp,rr,em,gr,as4,ap,err,llgr,fqdn .messages=8 .bytes=156
.gr-time=120 .eor=ip
     local.address=203.123.48.6 .as=37989 .id=203.123.48.6
.capabilities=mp,rr,gr,as4 .messages=272469 .bytes=24319937 .eor=""
     output.affinity=instance .procid=25 .filter-chain=Output_All
     input.affinity=instance .procid=24 ebgp
     multihop=yes hold-time=3m keepalive-time=1m uptime=7m33s800ms
last-started=2024-05-29 07:29:48 prefix-count=0

 9 E name="Routeview-v6-1"
     remote.address=2001:468:d01:33::113 .as=6447 .id=128.223.51.113
.capabilities=mp,rr,em,gr,as4,ap,err,llgr,fqdn .afi=ipv6 .messages=6
.bytes=124 .gr-time=120 .eor=""
     local.address=2405:fc00::6 .as=37989 .id=203.123.48.6
.capabilities=mp,rr,gr,as4 .afi=ipv6 .messages=68646 .bytes=7559819 .eor=""
     output.affinity=instance .procid=25 .filter-chain=Output_All
     input.affinity=instance .procid=24 ebgp
     multihop=yes hold-time=3m keepalive-time=1m uptime=5m12s770ms
last-started=2024-05-29 07:32:09 prefix-count=0

Thank you for a great project.

-- 
Sanjeev Gupta
+65 98551208     http://www.linkedin.com/in/ghane

**Comment by pfsinoz** [comment]
Hi Sanjeev,

Heh heh, the famous "have you tried turning it off and on again". Glad that it all worked and, yes, confirmed, the peerings are up.
```
Neighbor           V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
203.123.48.6       4      37989    317810      6482 20743720    0    0 01:41:28       969941        0 DCS1 Pte Ltd
2405:fc00::6       4      37989     80485      6358  6357642    0    0 01:39:07       196939        0 DCS1 Pte Ltd
```
Thank you for your support of the RouteViews Project and for sending us full IPv4 and IPv6 tables, we really appreciate it!

Philip
