### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by NNET-ELi** [routeviews/issues#101]
### Full Name

NNET

### ASN

142582

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

Hello, my goal is to contribute to the development and visualization of the Internet. Here is the information for building peers:
ASN: 142582
Source IPv4: 194.50.19.210
Source IPv6: 2a0f:5707:ab80:2582::1
BGP Password:  PFdw.2HB634W

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by pfsinoz** [comment]
Sorry for the delay in responding to set this peering up. We now have additional capacity on our multi-hop collectors at the University of Oregon. If you are still interested in setting up this multi-hop peering, please let me know, and I'll set up our end and provide the connection info.

**Comment by pfsinoz** [comment]
I'm closing the case now. If you'd still like to set up a multi-hop peering with RouteViews, please open a new request.
