### ISSUE TITLE
route-views.isc stopped producing data since 2023-08-09

### ISSUE THREAD

**Issue by digizeph** [routeviews/issues#102]
### Effected Services/Hosts

route-views.isc

### Details

RouteViews ISC collector stopped producing data since  2023-08-09. Both RIBs and updates files are affected. Did not see any announcements on the home page.
https://routeviews.org/route-views.isc/bgpdata/2023.08/RIBS/

![image](https://github.com/routeviews/issues/assets/659667/3c914812-9bcc-4bc2-b770-dd097e600389)

**Comment by hanskuhn** [comment]
Hi Mingwei,

Thanks for reaching out. I apologize for the lack of communication. There's now a post on our website. 😅

Our host for this collector had to move racks at PAIX and during the move our connectivity was lost. We are working to restore service, but there's no current estimate for return to service.

**Comment by digizeph** [comment]
I see that the collector is back online. Will close this issue. Thank you for your efforts!
