### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by chriselsen** [routeviews/issues#106]
### Full Name

Christian Elsen

### ASN

213151

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [x] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

80.81.196.225
2001:7f8::3:409f:0:1
185.1.166.237
2001:7f8:f2:e1:0:21:3151:1

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by pfsinoz** [comment]
We are now in a position to peer with you at LOC-IX Frankfurt as we have a new collector in place. If you are still interested in peering with RouteViews as per your original request, please reopen this case. Many thanks!

**Comment by chriselsen** [comment]
@pfsinoz Yes, I'm still interested. Github doesn't allow re-opening issues. Do you want me to create a new one?

**Comment by pfsinoz** [comment]
Hi Christian,

I've now set up the peering at LOC-IX. The IPv4 established almost immediately but the IPv6 one remains down. Here is the status:
```
Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
185.1.166.237   4     213151    348386        37        0    0    0 00:17:17       961265        0 AS213151 LLC
Neighbor                     V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
2001:7f8:f2:e1:0:21:3151:1   4     213151         3        11        0    0    0    never       Active        0 AS213151 LLC
```
Interestingly the error message we are getting for the IPv6 peering is that the peer is claiming it is in AS6447:
```
%NOTIFICATION: received from neighbor 2001:7f8:f2:e1:0:21:3151:1 2/2 (OPEN Message Error/Bad Peer AS) 4 bytes 00 00 19 2f
```
Hopefully this can be fixed. :-) 
Best wishes!

**Comment by chriselsen** [comment]
Sorry, there was a typo in the IPv6 config's ASN. That has been fixed now and both sessions are up. Thank you!
