### ISSUE TITLE
prefix v4

### ISSUE THREAD

**Issue by Nestaindomedia** [routeviews/issues#108]
### Observed Behavior

A bug happened! 🐛😨
please remove data ip 38.156.95.0/24 from our AS151006
because that not our ip
rview/route-views.ipv4.dump:38.156.95.0/24 3130 1239 38158 151006 151006 151006

we check from route view collector there is no prefix
route-views2.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24, version 46637480
Paths: (30 available, best #28, table default)
  Not advertised to any peer
  34224 38158 142307 142307 142307
    94.156.252.18 from 94.156.252.18 (94.156.252.25)
      Origin IGP, metric 0, valid, external, rpki validation-state: not found
      Community: 34224:333 34224:334 34224:2030
      Last update: Tue Sep  5 04:49:40 2023

route-views3.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24, version 48637602
Paths: (28 available, best #28, table default)
  Not advertised to any peer
  38001 38158 142307 142307 142307
    202.150.221.33 from 202.150.221.33 (10.11.33.29)
      Origin IGP, valid, external, rpki validation-state: not found
      Community: 38001:420 38001:2406 38001:3001 38001:8009
      Large Community: 55518:1000:2 55518:1001:1
      Last update: Tue Sep  5 08:36:02 2023

route-views4.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24, version 54472893
Paths: (23 available, best #23, table default)
  Not advertised to any peer
  34288 38158 142307 142307 142307
    109.233.180.32 from 109.233.180.32 (109.233.180.32)
      Origin IGP, valid, external, rpki validation-state: not found
      Community: 8714:65010 8714:65011 8714:65023 38158:65030 65500:50000 65500:59000 65500:59120 65500:59121
      Large Community: 8714:1000:2 8714:1001:1 8714:1001:2
      Last update: Tue Sep  5 11:48:09 2023

route-views6.routeviews.org> sh ip bgp 38.156.95.0/24
% Network not in table

route-views.eqix.routeviews.org> sh ip bgp 38.156.95.0/24 bestpath
BGP routing table entry for 38.156.95.0/24, version 13081142
Paths: (19 available, best #19, table default)
  Not advertised to any peer
  6939 38158 142307 142307 142307
    206.126.236.37 from 206.126.236.37 (216.218.253.247)
      Origin IGP, valid, external, best (Older Path), rpki validation-state: not found
      Last update: Mon Aug 28 11:34:26 2023

route-views.gorex.routeviews.org> sh ip bgp 38.156.95.0/24
% Network not in table

route-views.napafrica.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24, version 352501226
Paths: (14 available, best #14, table default)
  Not advertised to any peer
  37468 38158 142307 142307 142307
    196.60.8.60 from 196.60.8.60 (197.149.149.120)
      Origin IGP, metric 0, valid, external, rpki validation-state: not found
      Community: 37468:2000 37468:2500 37468:2510 37468:2512 37468:15000 37468:15100 37468:15101 37468:37468 38158:65030 55518:65012 55518:65021
      Large Community: 55518:1000:2 55518:1001:1
      Last update: Fri Sep  1 06:03:55 2023

route-views.nwax.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24, version 100935026
Paths: (2 available, best #2, table default)
  Not advertised to any peer
  1798 6939 38158 142307 142307 142307
    198.32.195.42 from 198.32.195.23 (192.149.16.251)
      Origin IGP, valid, external, rpki validation-state: not found
      Last update: Tue Aug 29 13:42:54 2023

route-views.paix.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24, version 141005
Paths: (6 available, best #6, table default)
  Not advertised to any peer
  49544 38158 142307 142307 142307
    198.32.176.191 from 198.32.176.95 (188.122.95.83)
      Origin IGP, metric 0, valid, external, rpki validation-state: not found
      Community: 24115:38158 24115:65023 38158:65030 49544:14000 49544:14106
      Large Community: 24115:1000:2 24115:1001:1 24115:1002:1 24115:1003:163 24115:1004:38158
      Last update: Mon Sep  4 11:00:09 2023

route-views.wide.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24
Paths: (2 available, best #1, table Default-IP-Routing-Table)
  Not advertised to any peer
  2497 6939 38158 142307 142307 142307
    202.249.2.169 from 202.249.2.169 (58.138.97.242)
      Origin IGP, localpref 100, valid, external, best
      Last update: Sun Sep  3 04:04:43 2023

route-views.sydney.routeviews.org> sh ip bgp 38.156.95.0/24 bestpath
BGP routing table entry for 38.156.95.0/24, version 115287228
Paths: (17 available, best #17, table default)
  Not advertised to any peer
  58511 38158 142307 142307 142307
    45.127.172.149 from 45.127.172.149 (103.247.3.101)
      Origin IGP, valid, external, best (AS Path), rpki validation-state: not found
      Community: 58511:200 58511:9008
      Large Community: 24115:1000:2 24115:1001:1 24115:1002:1 24115:1003:1 24115:1004:38158
      Last update: Tue Sep  5 13:00:21 2023

route-views.telxatl.routeviews.org> sh ip bgp 38.156.95.0/24 bestpath
BGP routing table entry for 38.156.95.0/24, version 219639862
Paths: (7 available, best #7, table default)
  Not advertised to any peer
  6939 38158 142307 142307 142307
    198.32.132.75 from 198.32.132.75 (216.218.252.254)
      Origin IGP, valid, external, best (AS Path), rpki validation-state: not found
      Last update: Mon Aug 28 11:34:25 2023

route-views.sg.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24
Paths: (21 available, best #18, table Default-IP-Routing-Table)
  Not advertised to any peer
  132337 38158 142307 142307 142307
    27.111.228.31 from 27.111.228.134 (172.16.1.102)
      Origin IGP, localpref 100, valid, external
      Last update: Fri Sep  1 02:59:01 2023

route-views.perth.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24, version 267475339
Paths: (16 available, best #15, table default)
  Not advertised to any peer
  6939 38158 142307 142307 142307
    198.32.212.10 from 198.32.212.254 (198.32.212.254)
      Origin IGP, metric 475, valid, external, rpki validation-state: not found
      Last update: Tue Aug 29 13:42:54 2023

route-views.sfmix.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24, version 303746740
Paths: (6 available, best #5, table default)
  Not advertised to any peer
  6939 38158 142307 142307 142307
    206.197.187.12 from 206.197.187.254 (206.197.187.254)
      Origin IGP, metric 1835, valid, external, rpki validation-state: not found
      Community: 64512:11 64512:21
      Large Community: 63055:64512:11 63055:64512:21
      Last update: Tue Aug 29 13:42:55 2023

route-views.soxrs.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24
Paths: (3 available, best #1, table Default-IP-Routing-Table)
  Not advertised to any peer
  6939 38158 142307 142307 142307
    185.1.27.63 from 185.1.27.1 (185.1.27.1)
      Origin IGP, metric 1605, localpref 100, valid, external, best
      Community: 13004:0
      Last update: Tue Aug 29 13:42:54 2023

route-views.mwix.routeviews.org> sh ip bgp 38.156.95.0/24
% Network not in table

route-views.amsix.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24, version 79019397
Paths: (26 available, best #23, table default)
  Not advertised to any peer
  267613 3356 2914 38158 142307 142307 142307
    80.249.213.223 from 80.249.213.223 (201.182.252.225)
      Origin IGP, metric 0, valid, external, rpki validation-state: not found
      Community: 5469:2200 5469:10850 5469:11000
      Last update: Wed Aug 30 03:44:14 2023

route-views.flix.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24, version 10861124
Paths: (12 available, best #12, table default)
  Not advertised to any peer
  61832 6939 38158 142307 142307 142307
    206.41.108.23 from 206.41.108.72 (10.0.0.136)
      Origin IGP, valid, external, rpki validation-state: not found
      Community: 26162:500
      Last update: Wed Aug 30 19:24:17 2023

route-views.uaeix.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24, version 129736830
Paths: (7 available, best #7, table default)
  Not advertised to any peer
  6939 38158 142307 142307 142307
    185.1.8.63 from 185.1.8.251 (185.1.8.251)
      Origin IGP, metric 10785, valid, external, rpki validation-state: not found
      Community: 65101:5079 65102:5000 65103:784 65104:142
      Large Community: 6695:1000:2 6695:1001:1
      Last update: Tue Aug 29 13:42:55 2023

route-views.ny.routeviews.org> sh ip bgp 38.156.95.0/24
BGP routing table entry for 38.156.95.0/24, version 45236820
Paths: (1 available, best #1, table default)
  Not advertised to any peer
  398465 6939 38158 142307 142307 142307
    206.82.104.185 from 206.82.104.185 (10.0.0.1)
      Origin IGP, valid, external, best (First path received), rpki validation-state: not found
      Community: 65101:2083 65102:2000 65103:840 65104:19
      Large Community: 6695:1000:2 6695:1001:1
      Last update: Tue Aug 29 13:42:54 2023

from another website

https://irrexplorer.nlnog.net/asn/AS151006

thanks

**Comment by kemp-rv** [comment]
We have removed the peer on route-views2 that was holding onto the old routing information.  All collectors now show the correct origin AS.  Closing issue.
