### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by edo660** [routeviews/issues#109]
### Full Name

On Q Communications

### ASN

7594

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by hanskuhn** [comment]
Hi,

Thanks for contributing to RouteViews! 

**If possible, we request full table export.  Please filter out NULL, RFC1918, and Default.
NOTE: we do not accept connections with ADD-PATH RX or TX enabled.**

## Sydney

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    45.127.173.66   4       7594        24         9        0    0    0    never         Idle        0 On Q Communications
    Neighbor              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:de8:6::7594:1    4       7594        24         8        0    0    0    never         Idle        0 On Q Communications
```

Here are our details:

fqdn: route-views.sydney.routeviews.org
asn: 6447
ip4: 45.127.172.100/24
ip6: 2001:de8:6::6447:1/64

## Brisbane
```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    218.100.76.5    4       7594        21        14        0    0    0    never         Idle        0 On Q Communications
    Neighbor                 V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:7fa:11:2:0:1daa:0:1 4       7594        21        14        0    0    0    never         Idle        0 On Q Communications
```

fqdn: route-views.perth.routeviews.org
asn: 6447
ip4: 218.100.52.52/23
ip6: 2001:7fa:11:4:0:192f:0:1/64
