### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by permarkermortensen** [routeviews/issues#111]
### Full Name

GlobalConnect

### ASN

31027

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [x] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by kemp-rv** [comment]
> 31027

We could peer at route-views.linx.routeviews.org.  Our side would be:

AS6447
        v4: 195.66.225.222
        v6: 2001:7f8:4::192f:1

If possible, we request full table export.  Please filter out NULL, RFC1918, and Default.
NOTE: we do not accept connections with ADD-PATH RX or TX enabled.

Thanks,
help@routeviews.org

**Comment by pfsinoz** [comment]
We are now in a position to peer at AMS-IX as we have a new collector in place. Please let us know by reopening this case if you would be interested in peering with RouteViews, as per your original request.
