### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by mertcangokgoz** [routeviews/issues#114]
### Full Name

Mertcan GOKGOZ

### ASN

216343

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [x] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

IPV4: 91.151.84.199
IPV6: 2a0f:6580:109:1337::1

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by pfsinoz** [comment]
Hello Mertcan and thank you for your interest in the RouteViews project. We now have additional capacity on our multi-hop route collectors to add new peers. However, noting your PeeringDB entry that says that AS216343 is a research/education AS investigating Internet Routing, we are wondering what peering with RouteViews would achieve? We only collect routes from network operators globally, and our goal is to collect views of the full BGP table in various parts of the world. Is this something AS216343 would be able to send to us with the multi-hop peering?

**Comment by mertcangokgoz** [comment]
I think there is very little support from Turkey to collect routes. I will add a few more providers from Turkey to the upstream in the future. I would love to contribute.

so I think we can make the routes more specific.

**Comment by pfsinoz** [comment]
Ok, thanks very much! Our collector details are:
```
IPv4: 128.223.51.113
IPv6: 2001:468:d01:33::113
ASN:  6447
FQDN: route-views7.routeviews.org
```
I've set up the multihop sessions now:
```
Neighbor                V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
91.151.84.199           4     216343         0         0        0    0    0    never      Connect        0 Mertcan GÖKGÖZ
2a0f:6580:109:1337::1   4     216343         0         0        0    0    0    never       Active        0 Mertcan GÖKGÖZ
```
Please let us know if you have any issues bringing up the multihop sessions. Thanks for supporting the RouteViews project.

**Comment by mertcangokgoz** [comment]
thank you I started the bgp session over ipv6.

**Comment by pfsinoz** [comment]
Yes indeed, so I see. :-)
```
2a0f:6580:109:1337::1       4     216343     91618        72   909689    0    0 01:09:15       200491        0 Mertcan GÖKGÖZ
```
Thank you for that. Would you be able to start the IPv4 one as well?

**Comment by mertcangokgoz** [comment]
Hello.

I will not be able to activate it for now until I can allocate an IPv4 address, thank you.

**Comment by pfsinoz** [comment]
Oh, isn't the 91.151.84.199 address the one you had allocated for the peering? In any case you should be able to use any IPv4 address already in use on your router.

**Comment by pfsinoz** [comment]
Any update as to when you might be able to establish the IPv4 peering at the address you proposed? Also, the IPv6 peering seems to be having lots of problems, going up and down regularly. Is there any issue? 

It is currently down:
```
Neighbor                 V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
91.151.84.199            4     216343         0         0        0    0    0    never      Connect        0 Mertcan GÖKGÖZ
2a0f:6580:109:1337::1    4     216343  12769101     32541        0    0    0 1d07h26m      Connect        0 Mertcan GÖKGÖZ
```
We are somewhat concerned about the resource consumption of the instability and the impact on our collector. If you would look into this please.

**Comment by mertcangokgoz** [comment]
The company I have a BGP connection with has been having a lot of problems lately, so the connections are not stable. There are a lot of such problems in Turkey. You can turn off the IPv4 connection, I'm trying to keep IPv6 connections stable, there seems to be no problem at the moment.

**Comment by pfsinoz** [comment]
Ok, I've turned the IPv4 connection off for now. Please let us know when you will be able to bring up the IPv4, if that becomes possible.
