### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by Gitdad** [routeviews/issues#117]
### Full Name

Jay Lehnert

### ASN

17766

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by hanskuhn** [comment]
Hi,

Thanks for contributing to the RouteViews project! We've established our peerings with you:

**If possible, we request full table export. Please filter out NULL, RFC1918, and Default.
NOTE: we do not accept connections with ADD-PATH RX or TX enabled.**

## SYD, Equinix

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    45.127.172.150  4      17766         0         0        0    0    0    never       Active        0 NEXON ASIA PACIFIC
    Neighbor              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:de8:6::1:7766:1  4      17766         0         0        0    0    0    never       Active        0 NEXON ASIA PACIFIC
```
Our details:

fqdn: route-views.sydney.routeviews.org
asn: 6447
ip4: 45.127.172.100
ip6: 2001:de8:6::6447:1

## MEL and BNE, IX Australia

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    218.100.76.125  4      17766         0         0        0    0    0    never       Active        0 NEXON ASIA PACIFIC
    218.100.78.159  4      17766         0         0        0    0    0    never       Active        0 NEXON ASIA PACIFIC
    Neighbor                 V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:7fa:11:1:0:4566:0:1 4      17766         0         0        0    0    0    never       Active        0 NEXON ASIA PACIFIC
    2001:7fa:11:2:0:4566:0:1 4      17766         0         0        0    0    0    never       Active        0 NEXON ASIA PACIFIC
```

Our details:

### MEL
fqdn: route-views.perth.routeviews.org
asn: 6447
ip4: 218.100.78.37
ip4: 2001:7fa:11:1:0:192f:0:1

### BNE

fqdn: route-views.perth.routeviews.org
asn: 6447
ip4: 218.100.76.18
ip6: 2001:7fa:11:2:0:192f:0:1
