### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by warwickw** [routeviews/issues#118]
### Full Name

Warwick Ward-Cox

### ASN

328832

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by pfsinoz** [comment]
Thanks for contributing to the RouteViews project!  

We are out of capacity at LINX for the time being but are happy to now accept peerings at our 2nd AMSIX collector.

We've configured the following EBGP sessions on the AMSIX RouteViews collector:

- asn:  6447
- ipv4: 80.249.213.84
- ipv6: 2001:7f8:1::a500:6447:2
- fqdn: amsix.ams.routeviews.org

Relevant `show bgp summary` output:
```
Neighbor                    V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
80.249.213.88               4     328832         0         0        0    0    0    never       Active        0 Network Platforms
2001:7f8:1:0:a500:32:8832:1 4     328832         0         0        0    0    0    never       Active        0 Network Platforms
```
Please filter out default route and RFC6490 address space.

NOTE: we do not accept addpath-RX or TX on connections.

Many thanks! :-)

**Comment by warwickw** [comment]
Thank you both ipv4 and ipv6 at AMS-IX sessions are established.

Our LINX session is still established but using our ASN 37497  I'd like to
change that to AS 328832

Can you do that?

Regards,
Warwick

**Comment by pfsinoz** [comment]
Hello Warwick!

Not a problem at all. I've swapped the peering over to AS 328832 now, and both the IPv4 and IPv6 sessions have established:
```
Neighbor                V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
195.66.224.25           4     328832  19735016    148840        0    0    0 00:03:26       934525        0 NetworkPlatforms
2001:7f8:4::5:480:1     4     328832     55065         5        0    0    0 00:03:41       190745        0 NetworkPlatforms
```
Many thanks!

Philip

**Comment by warwickw** [comment]
Awesome, thank you so much!
