### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by arraisfilho** [routeviews/issues#119]
### Full Name

Filho Arrais

### ASN

262462

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by hanskuhn** [comment]
Hello,

We have peering setup at Fortaleza:

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    45.184.146.7    4     262462         5        10        0    0    0    never         Idle        0 Aranet
    
    Neighbor               V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:12f8:0:9::146:7   4     262462         0         0        0    0    0    never      Connect        0 Aranet
```

Our details:

ASN: 6447
ip4: 45.184.144.184
ip6: 2001:12f8:0:9::184

Please filter out default route, null routes, RFC1918 routes,
and note that we currently do not allow add-path as a
capability during connect. We prefer full tables if possible.

Thanks for peering with Route Views!

---

Route Views collects routing data which is freely made available.
For reference, real-time monitoring of the data you are contributing to
this collector can be examined using the BGPStream/bgpreader toolkit.

### example 1. live data

  bgpreader -l -p routeviews -R <collector-name> -j <ASNUM>

### example 2. data past 24 hours

   bgpreader -I 24h -c <collector-name> -j <ASNUM>

For more information, please see: http://www.routeviews.org/routeviews/index.php/faq/
and https://bgpstream.caida.org/

If you have any questions, please contact us at help@routeviews.org
