### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by yhyuhuang** [routeviews/issues#123]
### Full Name

Peking University

### ASN

45090

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

120.53.103.17
2402:4e00:1207:2fff:0:9b02:d222:ce36

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by hanskuhn** [comment]
Hello,

Thanks for contributing to the RouteViews project. Our peering is up:


     Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ 
  Up/Down State/PfxRcd   PfxSnt Desc
     120.53.103.17   4      45090         6         6        0    0    0 
00:03:18            0        0 Tencent

     Neighbor                             V         AS   MsgRcvd   
MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
     2402:4e00:1207:2fff:0:9b02:d222:ce36 4      45090         6         
6        0    0    0 00:03:18            0        0 Tencent

Our peering details to configure your side:

   ip4: 128.223.51.108
   ip6: 2001:468:d01:33::80df:336c
   asn: 6447
   fqdn: route-views3.routeviews.org

Please filter out any default route, null routes, RFC1918 routes,
and note that we currently do not allow add-path as a
capability during connect. We prefer full tables, if possible.

Thanks!
