### ISSUE TITLE
certificate or srv record wrong for _imaps._tcp.routeviews.org

### ISSUE THREAD

**Issue by markrprior** [routeviews/issues#124]
### Observed Behavior

I run a script that tests for IPv6 services across a variety of domains, one of which is routeviews.org. One of the services it checks is email access via imap/pop3 and it does this by looking for SRV records. In routeviews.org's case it found `_imaps._tcp.routeviews.org.	10800	IN	SRV	0 1 993 imap.routeviews.org.`
imap.routeviews.org has a CNAME pointing at smtp.routeviews.org (which has a AAAA record).
My script then attempts to connect to this service (a number of domains have AAAA records on services that don't actually work) and when SSL/TLS is attempted it fails with a "Hostname mismatch" error. I haven't looked but I assume imap.routeviews.org isn't an alias on the certificate it is using (but smtp.routeviews.org is).

### Expected Behavior

There are two possible fixes:
1. add an alias for imap.routeviews.org to the certificate; or
2. remove the CNAME set and point the SRV record directly at smtp.routeviews.org

If either of these solutions are implemented then the SSL/TLS session should succeed and an appropriate IMAP banner will be displayed on connection.

### Relevant console output or logs

```shell
/usr/bin/openssl s_client -host 2001:468:d01:33:0:0:80df:330c -port 993 -servername 'imap.routeviews.org' -verify 5 -verify_hostname 'imap.routeviews.org' -verify_return_error -state -showcerts -nocommands -bugs -cipher 'DEFAULT@SECLEVEL=2'

verify depth is 5
SSL_connect:before SSL initialization
SSL_connect:SSLv3/TLS write client hello
SSL_connect:SSLv3/TLS write client hello
SSL_connect:SSLv3/TLS read server hello
SSL_connect:TLSv1.3 read encrypted extensions
depth=0 CN = mail.routeviews.org
verify error:num=62:Hostname mismatch
SSL3 alert write:fatal:bad certificate
SSL_connect:error in error
140268589122880:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1919:
CONNECTED(00000004)
---
no peer certificate available
---
No client certificate CA names sent
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2931 bytes and written 524 bytes
Verification error: Hostname mismatch
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 62 (Hostname mismatch)
---
```

**Comment by hanskuhn** [comment]
Hi Mark,

Thanks for the report. You caught me while I was trying to handle some of the domains and RRs that modern mail clients like to have. You bumped up my todo list to add those domains to the certificate issuance, and have the SRV _not_ point at a CNAME. 

Let me know if it looks OK.

cheers!

```
# dig SRV _imaps._tcp.routeviews.org. +short
0 1 993 smtp.routeviews.org.
```

```
---
SSL_connect:SSLv3/TLS read server session ticket
read R BLOCK
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN] Dovecot (Ubuntu) ready.
```

**Comment by markrprior** [comment]
Yes it looks fine to me now, thanks.

<img width="945" src="https://github.com/routeviews/issues/assets/6236685/69bb6ce6-9093-45b8-9867-32daf3ccb733">

FYI cells are: HTTP, SMTP, DNS, DNSSEC, NTP, XMPP, SIP, IMAPS/POP3, SUBMISSION and the colour represents IPv6 accessibility.
