### ISSUE TITLE
route-views.amsix rib file publication times

### ISSUE THREAD

**Issue by dmadory** [routeviews/issues#18]
### What buggy behavior would you like to report?

Is there any way to get route-views.amsix rib files to get published on predictable times like the other collectors?
For example:
route-views.amsix/bgpdata/2022.07/RIBS/rib.20220706.1411.bz2
route-views.amsix/bgpdata/2022.07/RIBS/rib.20220707.0959.bz2
route-views.amsix/bgpdata/2022.07/RIBS/rib.20220713.0237.bz2
route-views.amsix/bgpdata/2022.07/RIBS/rib.20220713.0256.bz2
route-views.amsix/bgpdata/2022.07/RIBS/rib.20220713.0402.bz2
route-views.amsix/bgpdata/2022.07/RIBS/rib.20220713.1846.bz2
Thank you!

### If the bug is fixed, what is the *expected behavior*?

In the filenames, the hours field is usually in increments of 2-hour blocks.

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by ryeleo** [comment]
> route-views.amsix/bgpdata/2022.07/RIBS/rib.20220706.1411.bz2
> route-views.amsix/bgpdata/2022.07/RIBS/rib.20220707.0959.bz2
> route-views.amsix/bgpdata/2022.07/RIBS/rib.20220713.0237.bz2
> route-views.amsix/bgpdata/2022.07/RIBS/rib.20220713.0256.bz2
> route-views.amsix/bgpdata/2022.07/RIBS/rib.20220713.0402.bz2
> route-views.amsix/bgpdata/2022.07/RIBS/rib.20220713.1846.bz2

Looking at the list, I can confirm that there was an outage around 7/6-7/13. However, there are still some odd "HHMM" signatures thereafter on 7/13: 0237, 0256, 0402, 1846.

> I wonder if this will smooth out over time. These behaviors might just be related to the recent outage we had.

Further investigation is required to root cause.

Thoughts and comments welcome, @routeviews/maintainers!

**Comment by kemp-rv** [comment]
@ryeleo You may have noticed, these are all 0-length RIB files... The size==14 is the hint.  Not sure what that all means, but that appears to be the case.  Those might have been router restarts, during the time there were no peers... not sure.

**Comment by ryeleo** [comment]
AMSIX collector has been posting at normal times again for months now 👍👍
