### ISSUE TITLE
Onboarding Matthew Luckie

### ISSUE THREAD

**Issue by matthewluckie** [routeviews/issues#24]
### Desired Username

mjl

### SSH Key

```shell
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDzAye8u7aR5J+39Bt9pXW53fe7qNxkqcqt6Xqf/5YTbmqHIXpBmQvlVN5dRg2acYIy1rrWxjN/d+T/1t4wOg84uuINrbAPc8nL/uTELFsDP1T+cz6TJWXN5BjUdH8IKfqgLSiZat9gC36zN5tiFNIzBDwSXgM16n9E1gByjGrd4+wMk7Gk1pETHySj6+9Doi3KTFS3qkmL+EjGQUP/BEdc1NFFzzTQu+SdVW1QkDePtY7RwLRzAmHIiruTIrZDG22KpiDfc86U9KmXvEXwGA9XbBc5DZbq3G0B5pGwFuHX9sBfzTWG5mHGqVBoUc5TH4gdv0JRyX6FjPDQhJz/aHlT mjl@macmini.luckie.org.nz
```

### New Maintainer Initial Tasks

- [x] Share Public SSH key (RSA, >2048 bytes)

### Existing Maintainer Tasks

- [ ] Add to ["Route Views Maintainers" GitHub Team](https://github.com/orgs/routeviews/teams/maintainers/members?add=true).
- [ ] Setup <username>@routeviews.org email account.
- [ ] Provide access to [our Grafana instance](http://rvmonitor.routeviews.org:3000/).
- [x] Deploy public SSH Key to RV infrastructure (via Ansible).
- [ ] Admit/ensure access to RV in PeeringDB.
- [ ] Ensure access to RV Slack.
- [ ] Provide access to the private Maintainer-only Slack channels. Today this includes: "peer requests" and "infrastructure".
- [ ] Share Route Views KeePass Master Password. (e.g., do this via RV Slack using [the "Secret Message" app](https://secretmessage.xyz/))
- [ ] Help the new member complete their first 'peer request'! (e.g., schedule a time within the next work-week)

### New Maintainer Final Tasks

- [ ] Set up your mail client with your new Route Views email address. Refer to our [mail configuration documentation](https://github.com/routeviews/infra/blob/master/docs/contribute/mail_settings.md)
- [ ] (BONUS) Set up the helpmail@routeviews.org email address also, giving you access to vast history of emails (credentials in [RV KeePass](https://github.com/routeviews/infra/blob/master/RouteViews.kdbx)).
- [ ] Ensure access to [Route Views Slack](https://routeviewsworkspace.slack.com).
- [ ] Review the [RV Maintainer Handbook (TODO update link to GH Pages)](https://github.com/routeviews/handbook).
- [ ] Set up a PeeringDB account, and ['request Affiliation' with Route Views  (ASN 6447) on your PeeringDB profile page](https://www.peeringdb.com/profile)
- [ ] Ensure login, and take a look through dashboards in [our Grafana instance](http://rvmonitor.routeviews.org:3000/).
- [ ] Complete your first peer request! 😁 (with help from an existing maintainer)

**Comment by ryeleo** [comment]
Going to close this for now since @matthewluckie really just needed SSH access to collectors
