### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by renatooj** [routeviews/issues#39]
### Full Name

Renato Jucá

### ASN

264409

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at ***all available exchanges*** (and omit Peer Address(es) field below)

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by ryeleo** [comment]
I went ahead and set up peering sessions on our end. You should be able to start sending us your full table of BGP prefixes once you establish the session on your side!

> **⚠ Note:** Please exclude default, null, and rfc1918 routes -- also ensure BGP ADD-PATH TX is disabled.

Relevant Route Views collector information:

* ASN: 6447
* IPv4 address: 45.6.52.213
* IPv6 address: 2001:12f8:0:2::213

Relevant ‘show bgp summary’ output:
```
    Neighbor        V         AS MsgRcvd MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd
    45.6.52.69      4     264409       0       0        0    0    0    never       Active
    45.6.54.95      4     264409  223057   43789        0    0    0 02w1d04h        55575
    Neighbor              V         AS MsgRcvd MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd
    2001:12f8:0:2::69     4     264409       0       0        0    0    0    never       Active
    2001:12f8:0:2::54:95  4     264409 3830564   43789        0    0    0 02w1d04h       156757
```

*If you're not familiar with [Route Views](http://www.routeviews.org/routeviews/), please see our [FAQ](http://www.routeviews.org/routeviews/index.php/faq/).*
