### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by egoistdream** [routeviews/issues#44]
### Full Name

DreamServer

### ASN

57050

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at ***all available exchanges*** (and omit Peer Address(es) field below)

### Peer Address(es)

2a10:fa80:10::246 2a10:fa80:10::247

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by pfsinoz** [comment]
Thank you for your interest in the RouteViews project. We are awaiting installation of additional capacity to support more multihop connections. We will only support same-address family peerings though. Please confirm if you are still interested in setting up a multi-hop peering, and we can work on that with you.

**Comment by dreamserver-ro** [comment]
Thank you for your message and for providing an update on the current status of the RouteViews project. We appreciate your efforts in expanding the capacity to accommodate more multihop connections.

Despite the delayed response, we remain keenly interested in setting up a BGP session with RouteViews.

Please consider this message as our confirmation of continued interest in establishing a multi-hop peering with RouteViews. We are ready to collaborate with you on the configuration process and eagerly await further instructions on how to proceed.

Thank you once again for your attention to this matter. We look forward to your guidance on the next steps.

**Comment by pfsinoz** [comment]
Great, thanks for your patience and continued interested in RouteViews. I'll set up a multihop session on one of our University of Oregon based collectors. Here are the details:
```
asn: 6447
ipv4: 128.223.51.15
ipv6: 2001:468:d01:33::80df:330f
fqdn: route-views4.routeviews.org
```
If you would please let us know your IPv4 end points, and confirm the IPv6 end point, then I will configure the EBGP multihop session with AS57050.

Please filter out default route and RFC6490 address space.  
NOTE: we do not accept addpath-RX or TX on connections.

Thanks!

**Comment by dreamserver-ro** [comment]
We use for ipv4: 212.81.56.227 and 212.81.56.228
For ipv6: 2a10:fa80:10::246 and 2a10:fa80:10::247

**Comment by pfsinoz** [comment]
Thank you for those details! I've now set up the multihop peering on our route-views4.routeviews.org collector:
```
Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
212.81.56.227   4      57050    159280         5 10145573    0    0 00:02:11       936095        0 DreamServer.ro
212.81.56.228   4      57050    159067         5 10145573    0    0 00:01:25       936095        0 DreamServer.ro

Neighbor             V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
2a10:fa80:10::246    4      57050     52168         5 12284795    0    0 00:02:15       190029        0 DreamServer.ro
2a10:fa80:10::247    4      57050     52225         5 12284795    0    0 00:02:04       190029        0 DreamServer.ro
```
Many thanks for helping support RouteViews!
