### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by jsaulsbery** [routeviews/issues#48]
### Full Name

Williams College

### ASN

11399

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at ***all available exchanges*** (and omit Peer Address(es) field below)

### Peer Address(es)

206.82.104.161
2001:504:36:0:1:8783:0:1

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by jsaulsbery** [comment]
Is there any additional info I can provide to assist with this request?

**Comment by hanskuhn** [comment]
Hi, Here's the details for peering with our NY collector:

ny collector
 - ip4: 206.82.105.7
 - ip6: 2001:504:36::192f:0:1
 - asn: 6447

The peerings are up on our side:

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    206.82.104.161  4      11399         0         0        0    0    0    never       Active        0 Williams College
    Neighbor                 V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:504:36:0:1:8783:0:1 4      11399         0         0        0    0    0    never       Active        0 Williams College
```

Route Views collects routing data which is freely made available.
For reference, real-time monitoring of the data you are contributing to
this collector can be examined using the BGPStream/bgpreader toolkit.

### example 1. live data

  bgpreader -l -p routeviews -R <collector-name> -j <ASNUM> 

### example 2. data past 24 hours

   bgpreader -I 24h -c <collector-name> -j <ASNUM> 

For more information, please see: http://www.routeviews.org/routeviews/index.php/faq/
and https://bgpstream.caida.org/

If you have any questions, please contact us at help@routeviews.org
