### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by YuzhenQin** [routeviews/issues#52]
### Full Name

YUZHEN NETWORK INC.

### ASN

AS211390

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at ***all available exchanges*** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

2a12:dd47:f601::1  
2a12:dd47:f602::1  
2a12:dd47:f603::1  
2a12:dd47:f604::1  
2a12:dd47:f605::1  
2a12:dd47:f606::1  
2a12:dd47:f607::1

### Multihop

- [X] Multihop

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by kemp-rv** [comment]
This request is somewhat problematic.  I believe we could peer at a regional exchange, but I do not see any overlap at exchanges where we exist.  For multi-hop however, I believe the hop-count and TTL will make these not feasible.
