### ISSUE TITLE
Peering Request [AS204508]

### ISSUE THREAD

**Issue by mlgtcode** [routeviews/issues#54]
### Full Name

Gatterer Manuel trading as MLGT

### ASN

AS204508

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at ***all available exchanges*** (*and skip the Peer Address(es) field below*)

### Peer Address(es)
- [X] 2001:7f8:f2:e1:0:20:4508:1  (LOC IX FRA)

### Multihop

- [X] <s>Multihop</s>

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by mlgtcode** [comment]
Session is configured at our end @ LocIX FRA.

**Comment by hanskuhn** [comment]
Our side of the peering is now up:

```
Neighbor                     V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:7f8:f2:e1:0:20:4508:1   4     204508         0         1        0    0    0    never       Active        0 Gatterer Manuel
```

Our ipv6 interface: 2001:7f8:f2:e1::6447:1
Our AS: 6447
