### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by renatooj** [routeviews/issues#60]
### Full Name

Renato de Oliveira Jucá

### ASN

264409

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

FL-IX

IPv4: 206.41.108.178
IPv6: 2001:504:40:108::1:178

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by kemp-rv** [comment]
These are now in the config.  Access to the data via:

	CLI:      telnet://route-views.flix.routeviews.org
	DATA:     rsync --list-only archive.routeviews.org::routeviews/route-views.flix/bgpdata
	DATA:     rsync --list-only archive2.routeviews.org::routeviews/route-views.flix/bgpdata
	REALTIME: (bgpstream v2) bgpreader -p routeviews-stream -R route-views.flix -t updates -j 264409
