### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by marek22k** [routeviews/issues#61]
### Full Name

Marek H.E. Kuethe / Bandura Communications

### ASN

202952

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

blinky.mk16.de / Germany - 193.148.249.165
arcadia.mk16.de / Germany - 91.228.52.232
august.mk16.de / USA - 165.140.142.43

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

### Questions

- Which route should I export to the RC? Only routes that I also export to my upstreams or all routes that I also export to my downstreams?

### Contact

- E-Mail: noc@mk16.de

**Comment by hanskuhn** [comment]
Hi Marek!

In response to your question, you might find our [FAQ](https://www.routeviews.org/routeviews/index.php/faq/) useful. The relevant section is
'What should my BGP policy on my Route Views peering look like?'

I'll setup the collector peering on our side and let you know when it it's up.

**Comment by hanskuhn** [comment]
The peering is up on our side:

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    91.228.52.232   4     202952         0         0        0    0    0    never      Connect        0 Bandura
    165.140.142.43  4     202952         0         0        0    0    0    never      Connect        0 Bandura
    193.148.249.165 4     202952         0         0        0    0    0    never      Connect        0 Bandura
```

**Comment by marek22k** [comment]
I am trying to configure the session and I get ´BGP Error: Required capability missing´.
´´´
$ birdc s p a routeviews
BIRD 2.0.12 ready.
Name       Proto      Table      State  Since         Info
routeviews BGP        ---        start  19:56:35.047  Idle          BGP Error: Required capability missing
  BGP state:          Idle
    Neighbor address: 128.223.51.105
    Neighbor AS:      6447
    Local AS:         202952
    Error wait:       43.702/60
    Last error:       BGP Error: Required capability missing
  Channel ipv6
    State:          DOWN
    Table:          master6
    Preference:     100
    Input filter:   REJECT
    Output filter:  (unnamed)
    Import limit:   200000
      Action:       block
    IGP IPv6 table: master6
´´´
