### ISSUE TITLE
[Peering Request] AS141776: Baoshuo Network

### ISSUE THREAD

**Issue by renbaoshuo** [routeviews/issues#63]
### Full Name

Baoshuo Network

### ASN

141776

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

- IPv4: `174.136.239.211`
- IPv6: `2406:840:e08f:1::1`

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by hanskuhn** [comment]
The peering is up on our side:

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    174.136.239.211 4     141776         0        37        0    0    0    never       Active        0 Baoshuo Network
    
    Neighbor                              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2406:840:e08f:1::1                    4     141776         0        37        0    0    0    never       Active        0 Baoshuo Network
```
