### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by Ticky131** [routeviews/issues#65]
### Full Name

RADISH NETWORKS

### ASN

399580

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

209.209.88.250
2606:5040::201

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by Ticky131** [comment]
Hello,

Looking to peer multihop from 209.209.88.250, 2606:5040::201

**Comment by hanskuhn** [comment]
The peering is up on our side:

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    209.209.88.250  4     399580         0         0        0    0    0    never      Connect        0 Radish Networks
    
    Neighbor                              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2606:5040::201                        4     399580         0         0        0    0    0    never      Connect        0 Radish Networks
```

**Comment by Ticky131** [comment]
Thanks - can you tell me your IP addresses to peer to and I'll get this done right away.

Chris Twa
Radish Networks

**Comment by hanskuhn** [comment]
Wecome! You were just a bit too quick. 😄  I edited the message above with the relevant details. Thanks for sharing your views with the RV project.
