### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by CoxallD** [routeviews/issues#66]
### Full Name

Superloop

### ASN

38195

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by hanskuhn** [comment]
I looked at your peeringdb entry and there's overlap in linx, amsix, singapore, and sydney.

Did you have a particular exchange you were looking to peer with us?

**Comment by CoxallD** [comment]
Hi Hans,

Typically we would peer at all available locations, if it should be only
one then Sydney is best.

Cheers,
Damien.

**Comment by hanskuhn** [comment]
Hi Damien,

I've configured peerings for Sydney:

Our ips for the Sydney peering:
  - v4: 45.127.172.100
  - v6: 2001:de8:6::6447:1

```
Neighbor        V    AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
45.127.172.89   4 38195       0       0        0    0    0 never    Active

Neighbor             V    AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
2001:de8:6::3:8195:1 4 38195       0       0        0    0    0 never    Active
```

and Perth:

Our ips for the Perth peering:
  - v4: 198.32.212.97
  - v6: 2001:7fa:11::192f:0:1

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    198.32.212.71   4      38195         0         0        0    0    0    never       Active        0 Superloop
  
    Neighbor                 V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:7fa:11::9533:0:1    4      38195         0         0        0    0    0    never       Active        0 Superloop
```
