### ISSUE TITLE
Peering IP Change RJ Huge-Networks

### ISSUE THREAD

**Issue by renatooj** [routeviews/issues#70]
### Full Name

Renato de Oliveira Jucá

### ASN

264409

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

Hello Routeviews Team,

I would like to reconfigure our Peering in RJ, Please use the news IPs.

IPv4: **45.6.55.6**
IPv6:  **2001:12f8:0:2::55:6**

Best Regards,

Renato Jucá

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by hanskuhn** [comment]
IPs have been changed. 

```
 Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
 45.6.55.6       4     264409     14833        39        0    0    0 00:18:23        48679        0 Huge Networks -
   
 Neighbor              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
 2001:12f8:0:2::55:6   4     264409     53640        39        0    0    0 00:18:23       161727        0 Huge Networks -
```
