### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by peer-1** [routeviews/issues#71]
### Full Name

Peer 1 Internet Service

### ASN

1031

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by hanskuhn** [comment]
Here are the details for our collectors:

flix collector
 - ip4: 206.41.108.119/24
 - ip6: 2001:504:40:108::1:119/64
 - as: 6447

fortaleza collector
 - ip4: 45.184.144.184
 - ip6: 2001:12f8:0:9::184
 - as: 6447

linx collector
 - ip4: 195.66.237.222/22
 - ip6: 2001:7f8:4:1::192f:1/64
 - as: 6447

rio collector
 - ip4: 45.6.52.213
 - ip6: 2001:12f8:0:2::213
 - as: 6447

saopaulo collector
 - ip4: 187.16.219.166/20
 - ip6: 2001:12f8::219:166/64
 - as: 6447

We've enabled these peering sessions so you are ready to bring up your side:

```
saopaulo:

    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    187.16.214.103  4       1031        52        52        0    0    0    never         Idle        0 Peer 1 Internet
    187.16.217.158  4       1031         0         0        0    0    0    never      Connect        0 Peer 1 Internet

    Neighbor           V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:12f8::214:103 4       1031        56        55        0    0    0    never         Idle        0 Peer 1 Internet

flix:

   Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    206.41.108.179  4       1031        64        63        0    0    0    never         Idle        0 Peer 1 Internet

    Neighbor               V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:504:40:108::1:179 4       1031        64        58        0    0    0    never         Idle        0 Peer 1 Internet

fortaleza:

    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    45.184.147.17   4       1031        64        64        0    0    0    never         Idle        0 Peer 1 Internet

    Neighbor               V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:12f8:0:9::147:17  4       1031        62        62        0    0    0    never         Idle        0 Peer 1 Internet

linx:

    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    195.66.231.48   4       1031        64        64        0    0    0    never         Idle        0 Peer 1 Internet

    Neighbor                V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:7f8:4::407:1       4       1031        64        64        0    0    0    never         Idle        0 Peer 1 Internet

rio:

    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    45.6.53.250     4       1031         0         0        0    0    0    never      Connect        0 Peer 1 Internet

    Neighbor              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:12f8:0:2::53:250 4       1031        54        54        0    0    0    never         Idle        0 Peer 1 Internet
```

Route Views collects routing data which is freely made available.
For reference, real-time monitoring of the data you are contributing to
this collector can be examined using the BGPStream/bgpreader toolkit.

### example 1. live data

  bgpreader -l -p routeviews -R <collector-name> -j <ASNUM> 

### example 2. data past 24 hours

   bgpreader -I 24h -c <collector-name> -j <ASNUM> 

For more information, please see: http://www.routeviews.org/routeviews/index.php/faq/
and https://bgpstream.caida.org/

If you have any questions, please contact us at help@routeviews.org
