### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by edgenative** [routeviews/issues#73]
### Full Name

Kerfuffle

### ASN

35008

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

194.246.109.5
2001:67c:760:a::5

### Multihop

- [x] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by hanskuhn** [comment]
Hi, 

Here are the peering details for the Route Views collectors:

route-views5 multihop:
 - ip4: 128.223.51.105
 - ip6: 2001:468:d01:33::80df:3369
 - asn: 6447

sfmix:
 - ip4: 206.197.187.28
 - ip6: 2001:504:30::ba00:6447:1/64
 - asn: 6447

The peering sessions are up on our side:

```
route-views5:

    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    194.246.109.5   4      35008         0         0        0    0    0    never       Active        0 Kerfuffle, LLC

    Neighbor                              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:67c:760:a::5                     4      35008         0         0        0    0    0    never       Active        0 Kerfuffle, LLC

sfmix:

    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    206.197.187.41  4      35008         0         0        0    0    0    never       Active        0 Kerfuffle, LLC

    Neighbor                 V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:504:30::ba03:5008:1 4      35008         0         0        0    0    0    never       Active        0 Kerfuffle, LLC
```

Route Views collects routing data which is freely made available.
For reference, real-time monitoring of the data you are contributing to
this collector can be examined using the BGPStream/bgpreader toolkit.

### example 1. live data

  bgpreader -l -p routeviews -R <collector-name> -j <ASNUM> 

### example 2. data past 24 hours

   bgpreader -I 24h -c <collector-name> -j <ASNUM> 

For more information, please see: http://www.routeviews.org/routeviews/index.php/faq/
and https://bgpstream.caida.org/
