### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by cr0gers** [routeviews/issues#77]
### Full Name

Chris Rogers

### ASN

19529

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

2602:fd10:10::
207.2.124.0
2602:fd10:20::
207.2.125.0

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by hanskuhn** [comment]
Peering session is up on our side:

```    
     Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    207.2.124.0     4      19529         0         0        0    0    0    never      Connect        0 Chris Rogers
    207.2.125.0     4      19529         0         0        0    0    0    never      Connect        0 Chris Rogers
    
    Neighbor                              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2602:fd10:10::1                       4      19529         0         0        0    0    0    never      Connect        0 Chris Rogers
    2602:fd10:20::1                       4      19529         0         0        0    0    0    never      Connect        0 Chris Rogers
```

**Comment by cr0gers** [comment]
v4 sessions are up.

It looks like your v6 sessions were configured with an incorrect neighbor IP. Neighbors should be 2602:fd10:10:: and 2602:fd10:20::. (No "1" at the end of the v6 neighbor IPs.)

**Comment by cr0gers** [comment]
v4 sessions are up.

It looks like your v6 sessions were configured with an incorrect neighbor IP. Neighbors should be 2602:fd10:10:: and 2602:fd10:20::. (No "1" at the end of the v6 neighbor IPs.)

**Comment by hanskuhn** [comment]
Hi. 

I have to laugh. 😄  I configured them as you specified them, but some part of our tooling wouldn't accept it as a valid address. I'm not sure if it was FRR or something else.

I'll re-open this issue and create a separate issue to track this and see if there's a possible resolution. I'm not sure what I can do if FRR won't accept this address form.

If I can't find a fix, is it possible you can provide a different v6 peering address? (I know this isn't likely, but want to understand the options available to us).

thanks,
Hans

**Comment by cr0gers** [comment]
Hi Hans, I'm sure I can find another /128 to use for the peering IP, but I'd really prefer not to. 😉

**Comment by hanskuhn** [comment]
I found the problem once I had time to look at this. It was a YAML parsing error. Simply quoting the  v6 address cause the validation to succeed:

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    207.2.124.0     4      19529   4018524     44983        0    0    0 1d03h13m       933997        0 Chris Rogers
    207.2.125.0     4      19529   4050315     44900        0    0    0 3d10h59m       933830        0 Chris Rogers
    Neighbor                              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    602:fd10:20::                         4      19529         0         0        0    0    0    never      Connect        0 Chris Rogers
    2602:fd10:10::                        4      19529     46568         4        0    0    0 00:00:46       175190        0 Chris Rogers
```

Thanks for your patience

**Comment by cr0gers** [comment]
Thanks! I see one of the v6 sessions up now. Unfortunately it seems that
the leading "2" is missing from one of the v6 neighbors in your config.
"2602" instead of "602".

**Comment by hanskuhn** [comment]
fixed.
