### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by samshamretn** [routeviews/issues#78]
### Full Name

Sam Sham

### ASN

9002

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

80.249.209.216
2001:7f8:1::a500:9002:1
195.66.224.193
2001:7f8:4::232a:1
27.111.229.103
2001:de8:4::9002:1

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by hanskuhn** [comment]
Hi. Here's the details for how to peer with two of the three collectors you've requested. I'll keep this request open until we bring up Singapore, but feel free to enable bring up these peerings:

amsix
 - ip4: 80.249.214.5
 - ip6: 2001:7F8:1::A500:6447:1
 - asn: 6447

linx
 - ip4: 195.66.225.222
 - ip6: 2001:7f8:4::192f:1
 - asn: 6447

The peering sessions are up on our side:

```
amsix:

 Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    80.249.209.216  4       9002         0         0        0    0    0    never      Connect        0 RETN
    Neighbor                     V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:7f8:1::a500:9002:1      4       9002         0         0        0    0    0    never      Connect        0 RETN

linx:

    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    195.66.224.193  4       9002         0         0        0    0    0    never      Connect        0 RETN
    Neighbor                V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:7f8:4::232a:1      4       9002         0         0        0    0    0    never      Connect        0 RETN
```
Route Views collects routing data which is freely made available.
For reference, real-time monitoring of the data you are contributing to
this collector can be examined using the BGPStream/bgpreader toolkit.

### example 1. live data

  bgpreader -l -p routeviews -R <collector-name> -j <ASNUM> 

### example 2. data past 24 hours

   bgpreader -I 24h -c <collector-name> -j <ASNUM> 

For more information, please see: http://www.routeviews.org/routeviews/index.php/faq/
and https://bgpstream.caida.org/

If you have any questions, please contact us at help@routeviews.org

**Comment by hanskuhn** [comment]
The Singapore peerings are up now. The .sg collector details are:

 - ip4: 27.111.228.208
 - ip6: 2001:de8:4::6447:1
 - asn: 6447
