### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by zejar** [routeviews/issues#82]
### Full Name

Alpine North

### ASN

60557

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

2a0d:8d06:f::94c3
176.119.215.4
2a0d:8d06:f::e1ee
176.119.215.5

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by zejar** [comment]
The sessions with AS206064 can also be removed. This means the sessions to the IP 2001:678:cec:f000:e808:7b96:311d:e4bc from collectors 3 & 6.

**Comment by hanskuhn** [comment]
The new peering is up on route-views5.routeviews.org:

```
 Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    176.119.215.4   4      60557         0         0        0    0    0    never      Connect        0 Alpine North LTD
    176.119.215.5   4      60557         0         0        0    0    0    never      Connect        0 Alpine North LTD
    Neighbor                              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2a0d:8d06:f::94c3                     4      60557         0         0        0    0    0    never      Connect        0 Alpine North LTD
    2a0d:8d06:f::e1ee                     4      60557         0         0        0    0    0    never      Connect        0 Alpine North LTD
```

I removed the peerings on route-views3 and route-views6 for AS206064.

Let me know if you have any questions.
