### ISSUE TITLE
Peering Request from AS329035

### ISSUE THREAD

**Issue by MuaazTeladia** [routeviews/issues#83]
### Full Name

Telsense Technology Group

### ASN

329035

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by hanskuhn** [comment]
The peering is up on our side:

```
   Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    196.60.10.230   4     329035         0         1        0    0    0    never       Active        0 Telsense Technology
    Neighbor              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:43f8:6d0::10:230 4     329035         0         1        0    0    0    never       Active        0 Telsense Technology
```

Our router information is as follows:

hostname: route-views.napafrica.routeviews.org 
asn: 6447
ip4: 196.60.9.68/22
ip6: 2001:43f8:6d0::9:68/64

Route Views collects routing data which is freely made available.
For reference, real-time monitoring of the data you are contributing to
this collector can be examined using the BGPStream/bgpreader toolkit.

### example 1. live data

  bgpreader -l -p routeviews -R <collector-name> -j <ASNUM> 

### example 2. data past 24 hours

   bgpreader -I 24h -c <collector-name> -j <ASNUM> 

For more information, please see: http://www.routeviews.org/routeviews/index.php/faq/
and https://bgpstream.caida.org/

If you have any questions, please contact us at help@routeviews.org
