### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by chrisbish** [routeviews/issues#84]
### Full Name

DSM Group

### ASN

48070

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

LINX LON1

195.66.226.254
2001:7f8:4::bbc6:1

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by hanskuhn** [comment]
The peering is up on our side:

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    195.66.226.254  4      48070         0         0        0    0    0    never      Connect        0 DSM (GB) Limited
    Neighbor                V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:7f8:4::bbc6:1      4      48070         0         0        0    0    0    never      Connect        0 DSM (GB) Limited
```

Our details:

as: 6447
ip4: 128.223.51.108
ip6: 2001:468:d01:33::80df:336c
fqdn: route-views3.routeviews.org

**Comment by chrisbish** [comment]
Shouldn't this be your LINX LON1 details?
195.66.225.222
2001:7f8:4::192f:1

RP/0/RSP0/CPU0:teleh-nrth-9k-core01#show bgp ipv4 unicast neighbors 195.66.225.222
Thu Jun  8 07:57:58.872 GMT

BGP neighbor is 195.66.225.222
 Remote AS 6447, local AS 48070, external link
 Description: PEERING: RouteViews (AS6447)
 Remote router ID 0.0.0.0
  BGP state = Idle

**Comment by hanskuhn** [comment]
Take 2! 📣

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    195.66.226.254  4      48070    130892        39        0 8710    0 00:06:16       855119        0 DSM (GB) Limited
    Neighbor                V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:7f8:4::bbc6:1      4      48070     46174        39        0    0    0 00:06:16       172363        0 DSM (GB) Limited
```

- as: 6447
- ip4: 195.66.225.222
- ip6: 2001:7f8:4::192f:1
- fqdn: route-views.linx.routeviews.org

Thanks for giving us a chance to fix this and reach out if you need anything else.
