### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by potvinp** [routeviews/issues#85]
### Full Name

Accuris Technologies Ltd.

### ASN

52210

### PeeringDB Integration

- [x] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

23.130.139.83
2602:fcd3:1:1::13

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by pfsinoz** [comment]
Apologies for the delay in responding to the multihop peering request while we increased our collector capacity at the University of Oregon. We are now in a position to set up the peering. Please let us know if you are still interested, and I can then set up the sessions and provide our new collector's details. Thanks for your interest in the RouteViews project.

**Comment by potvinp** [comment]
We are still interested!

**Comment by pfsinoz** [comment]
Thanks Peter! Our new collector details are:
```
IPv4: 128.223.51.113
IPv6: 2001:468:d01:33::113
ASN:  6447
FQDN: route-views7.routeviews.org
```
I have set up the multihop peering configuration now:
```
Neighbor            V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
23.130.139.83       4      52210         0         1        0    0    0    never       Active        0 Accuris
2602:fcd3:1:1::13   4      52210         0         1        0    0    0    never       Active        0 Accuris
```
Please let us know if you have any issues bringing up the peering. Thanks for supporting the RouteViews project!

**Comment by pfsinoz** [comment]
The BGP sessions have been up and stable for over a week now.
```
Neighbor              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
23.130.139.83         4      52210   9249042     31146 44645721    0    0 01w5d02h       939643        0 Accuris
2602:fcd3:1:1::13     4      52210   6604549     31135 18894323    0    0 01w5d03h       199511        0 Accuris
```
