### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by pcela** [routeviews/issues#86]
### Full Name

Piotr Chrzanowski

### ASN

199763

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

LocIX - 2001:7f8:f2:e1:0:19:9763:1

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by pfsinoz** [comment]
Hello Piotr... I don't see any PeeringDB entry for AS199763 listing a presence at LOC-IX in Frankfurt. If you are still interested in peering with RouteViews there, please update your PeeringDB entry as our automation tools rely on accurate PeeringDB entries, and then reopen this case.

Thanks!

**Comment by pcela** [comment]
Entries in PeeingDB are current, I am no longer a member of the IXP "LocIX". In addition, 10 months have passed since submitting a peering application, and for such a period it can change a lot.

**Comment by pfsinoz** [comment]
Understood, thanks for getting back to us, Piotr! :-)
