### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by IvanAlbertini** [routeviews/issues#87]
### Full Name

Huge Networks

### ASN

264409

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

[LOCIX Frankfurt](https://www.peeringdb.com/ix/2084)
6447
10G
RS PEER
185.1.167.72
2001:7f8:f2:e1::6447:1

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by IvanAlbertini** [comment]
Hi team,
need anything more to do the peering?

**Comment by hanskuhn** [comment]
Hello,

Can you update your peeringdb record to include your presence at LOCIX Frankfurt? We use peeringdb to drive our automation and validate our peers.

Thanks!

**Comment by pfsinoz** [comment]
Hello Ivan... I still don't see any update in  your PeeringDB record re your presence at LOC-IX in Frankfurt. Once this is done and you'd still like to peer with RouteViews there, please reopen this case.

Thanks!
