### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by Fr3DBr** [routeviews/issues#88]
### Full Name

FNX TECNOLOGIA LTDA

### ASN

60503

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

IX.BR / PTT-SP
v4: 187.16.214.32
v6: 2001:12f8::214:32

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by hanskuhn** [comment]
Our side is up:

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    187.16.214.32   4      60503         0         0        0    0    0    never      Connect        0 FNX Tecnologia LTDA
    Neighbor           V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2001:12f8::214:32  4      60503         0         0        0    0    0    never      Connect        0 FNX Tecnologia LTDA
```

Here are the connection details:

    as: 6447
    ip4: 187.16.219.166
    ip6: 2001:12f8::219:166

Thanks for peering with us!
