### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by paulhoogsteder** [routeviews/issues#90]
### Full Name

i3D.net

### ASN

49544

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

188.122.95.61 2a00:1630::61

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by hanskuhn** [comment]
The peerings are up on our side:

```
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    188.122.95.61   4      49544         0         0        0    0    0    never      Connect        0 i3D.net
    Neighbor                              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2a00:1630::61                         4      49544         0         0        0    0    0    never      Connect        0 i3D.net
```

Our details:

- asn: 6447
- ip4: 128.223.51.105
- ip6: 2001:468:d01:33::80df:3369

collector fqdn: route-views5.routeviews.org
