### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by brunovasconceloss** [routeviews/issues#96]
### Full Name

Huge Networks

### ASN

264409

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

Hello Routeviews Team,

I would like to formally request the establishment of a peering agreement between Huge Networks (AS264409), and 
RouteViews.

Location: Fortaleza - CE (ATM)
IPv4: 45.184.147.74
IPv6: 2001:12f8:0:9::147:74

PeeringDB: https://www.peeringdb.com/net/8002

Best Regards,

Bruno Vasconcelos.

### Multihop

- [ ] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by brunovasconceloss** [comment]
Hi team,

Do you need anything else to do the peering?

**Comment by brunovasconceloss** [comment]
Hi team,

Do you need anything else to do the peering?

**Comment by hanskuhn** [comment]
The peering is up:

```
Neighbor               V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
45.184.147.74   4     264409         0         0        0    0    0    never      Connect        0 Huge Networks
2001:12f8:0:9::147:74  4       1031       232       231        0    0    0    never         Idle        0 Huge Networks
```

Here's out details for your connection:

```
ip4: 45.184.144.184
ip6: 2001:12f8:0:9::184
asn: 6447
```

Let us know if you have any questions and thanks for your patience!
