### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by csch42** [routeviews/issues#97]
### Full Name

serve-u Buchholz & Sünderhauf GbR

### ASN

13058

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

2a0c:7286:2736::66
192.108.73.66

Greetings to hak from csch! 😉

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by hanskuhn** [comment]
Our side is up:

```    
    Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    192.108.73.66   4      13058         0         0        0    0    0    never       Active        0 serve-u - Buchholz
    Neighbor                              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
    2a0c:7286:2736::66                    4      13058         0         0        0    0    0    never       Active        0 iserve-u - Buchholz
```

Our details

```
  ip4:  128.223.51.105
  ip6: 2001:468:d01:33::80df:3369
  asn: 6447
  fqdn: route-views5.routeviews.org
```

Please filter out default route, null routes, RFC1918 routes,
and note that we currently do not allow add-path as a
capability during connect.

Thanks for peering with RouteViews!
