### ISSUE TITLE
Peering Request with Route Servers / BGP Freecore

### ISSUE THREAD

**Issue by erickhuge** [routeviews/issues#99]
### Full Name

Grupo YAX

### ASN

264409

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

Hi there,

We run BGP free-core on Routers PE / Edge. Because of that, I would like to verify if is possible to establish the IPv4/IPv6 sessions through EBGP Multihop with our Route Servers?

IP: 167.114.47.224
AS: 264409

Thanks in advance.

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by pfsinoz** [comment]
Erick, let's track this one under https://github.com/routeviews/issues/issues/120, please, and I'll close this request.
